-- 1. Buat tabel Categories
CREATE TABLE categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text UNIQUE NOT NULL,
  name text NOT NULL
);

-- 2. Buat tabel Projects
CREATE TABLE projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL,
  category_id bigint REFERENCES categories(id) ON DELETE RESTRICT,
  image text NOT NULL,
  image_alt text NOT NULL,
  year integer NOT NULL,
  featured boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Insert Dummy Data untuk Categories
INSERT INTO categories (id, slug, name) VALUES
(1, 'video', 'Video'),
(2, 'social-media', 'Social Media'),
(3, 'branding', 'Branding'),
(4, 'photography', 'Photography');

-- 4. Insert Dummy Data untuk Projects (diambil dari data/portfolio.ts)
INSERT INTO projects (id, title, description, category_id, image, image_alt, year, featured) VALUES
(1, 'Lifestyle Brand Campaign', 'Campaign visual dengan short-form video dan social media assets.', 3, 'https://images.unsplash.com/photo-1492724441997-5dc865305da7?auto=format&fit=crop&w=1600&q=90', 'Lifestyle brand campaign being filmed outdoors', 2025, true),
(2, 'Behind the Edit', 'Eksperimen video yang menampilkan proses editing dan sound design.', 1, 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=1600&q=90', 'Video editing timeline on a laptop', 2025, true),
(3, 'Weekly Social Series', 'Serial konten visual untuk membangun konsistensi brand di media sosial.', 2, 'https://images.unsplash.com/photo-1551818255-e6e10975bc17?auto=format&fit=crop&w=1600&q=90', 'Creator recording a social media video', 2024, false),
(4, 'Creative Equipment Shoot', 'Pemotretan peralatan kreatif untuk dokumentasi dan promosi produksi.', 4, 'https://images.unsplash.com/photo-1492619375914-88005aa9e8fb?auto=format&fit=crop&w=1600&q=90', 'Camera and creative equipment ready for a shoot', 2024, false);
