-- 1. Buat Tabel Learning
CREATE TABLE learning (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  icon_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Buat Tabel Profile (hanya 1 baris)
CREATE TABLE profile (
  id INT PRIMARY KEY DEFAULT 1,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  location TEXT NOT NULL,
  email TEXT NOT NULL,
  whatsapp TEXT NOT NULL,
  link_cv TEXT NOT NULL,
  short_bio TEXT NOT NULL,
  long_bio TEXT NOT NULL,
  availability TEXT NOT NULL,
  skill TEXT NOT NULL,
  summaries JSONB DEFAULT '[]'::jsonb,
  stats JSONB DEFAULT '[]'::jsonb,
  social_links JSONB DEFAULT '[]'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT single_row CHECK (id = 1) -- Memaksa hanya ada 1 baris
);

-- 3. Insert Data Dummy Learning
INSERT INTO learning (name, description, icon_name) VALUES
('Jaz Academy Multimedia', 'Pelatihan Multimedia & Content Creator dengan fokus pada produksi video, fotografi dasar, dan komunikasi visual.', 'CloudArrowUpIcon'),
('Udemy • CapCut & Premiere Pro', 'Kursus editing yang melatih cutting, audio mixing, color correction, caption, dan format video untuk berbagai platform.', 'LockClosedIcon'),
('MCC • Content strategy course', 'Belajar menyusun content pillar, membuat kalender konten, membaca insight, dan mengembangkan ide yang konsisten.', 'ArrowPathIcon'),
('Jazmedia • Visual storytelling', 'Mempraktikkan dasar scriptwriting, shot composition, camera movement, dan storytelling untuk video pendek.', 'FilmIcon');

-- 4. Insert Data Dummy Profile
INSERT INTO profile (
  id, name, role, location, email, whatsapp, link_cv, short_bio, long_bio, availability, skill, summaries, stats, social_links
) VALUES (
  1, 
  'Gilang Raka Aditya', 
  'Content Creator & Video Editor', 
  'Jakarta, Indonesia', 
  'hello@rakaaditya.com', 
  'https://wa.me/6281234567890', 
  'https://drive.google.com/file/d/1a2b3c4d5e6f7g8h9i0j/view?usp=sharing', 
  'I turn ideas, stories, and everyday moments into sharp visual content for brands, communities, and personal projects.', 
  'As a content creator and video editor, I work from the first idea to the final upload. My work combines visual storytelling, intentional editing, and a practical understanding of how people discover content online.', 
  'available', 
  'I am currently a multimedia student, building a practical foundation in visual communication while sharpening my craft through courses, personal projects, and collaborative productions.',
  '[
    {"name": "Creative direction", "description": "I develop visual concepts, moodboards, and content plans that give every story a clear point of view.", "icon_name": "CloudArrowUpIcon"},
    {"name": "Video editing", "description": "From rough cut to final export, I edit short-form and long-form videos with rhythm, pacing, sound, and captions in mind.", "icon_name": "LockClosedIcon"},
    {"name": "Social content", "description": "I create platform-ready reels, carousels, and behind-the-scenes content that feels native to each audience.", "icon_name": "ServerIcon"}
  ]'::jsonb,
  '[
    {"id": 1, "name": "Personal clients", "value": "18+"},
    {"id": 2, "name": "Collaborated with", "value": "12"},
    {"id": 3, "name": "Creative partners", "value": "24"}
  ]'::jsonb,
  '[
    {"id": 1, "label": "LinkedIn", "icon_name": "PresentationChartBarIcon", "href": "https://www.linkedin.com", "description": "Connect Professionally"},
    {"id": 2, "label": "Instagram", "icon_name": "CameraIcon", "href": "https://www.instagram.com", "description": "Behind The Scenes"},
    {"id": 4, "label": "YouTube", "icon_name": "PlayIcon", "href": "https://www.youtube.com", "description": "Subscribe my channel"}
  ]'::jsonb
);

-- 5. Konfigurasi Row Level Security (RLS)
ALTER TABLE learning ENABLE ROW LEVEL SECURITY;
ALTER TABLE profile ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on learning" ON learning FOR SELECT USING (true);
CREATE POLICY "Allow public read access on profile" ON profile FOR SELECT USING (true);

CREATE POLICY "Allow authenticated users to all on learning" ON learning FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated users to update profile" ON profile FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
